config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  get "terms/index", to: "terms#index", as: "terms"
  get "privacy_policy/index", to: "privacy_policy#index", as: "privacy_policy"
  get "contact/index"
  get "dashboard", to: "dashboard#index", as: "dashboard"
  get "contact", to: "contact#index", as: "contact"
  get "landing/index"
  resources :privacy_policy, only: [ :index ]
  resources :terms, only: [ :index ]
  resources :dashboard, only: [ :index ]
  resources :mentors
  resources :mentees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "landing#index"
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  field :sender_id, type: String
  field :receiver_id, type: String
  field :content, type: String

  belongs_to :sender, class_name: "User", inverse_of: :sent_messages
  belongs_to :receiver, class_name: "User", inverse_of: :received_messages
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to messages_path, status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:sender_id, :receiver_id, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sender_id, style: "display: block" %>
    <%= form.text_field :sender_id %>
  </div>

  <div>
    <%= form.label :receiver_id, style: "display: block" %>
    <%= form.text_field :receiver_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Sender:</strong>
    <%= message.sender_id %>
  </p>

  <p>
    <strong>Receiver:</strong>
    <%= message.receiver_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= message.content %>
  </p>

</div>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Messages" %>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>